version: '3.7'
services:
  www:
    image: nginx:latest
    ports:
      - 8443:443
      - 8080:80
    volumes:
      - type: bind
        source: ./www.anveshak.in.crt
        target: /etc/nginx/conf.d/www.anveshak.in.crt
      - type: bind
        source: ./www.anveshak.in.pem
        target: /etc/nginx/conf.d/www.anveshak.in.pem
      - type: bind
        source: ./www_anveshak.conf
        target: /etc/nginx/conf.d/www_anveshak.conf
      
  api:
    image: nginx:latest
    ports:
      - 9443:443
      - 9090:80
    volumes:
      - type: bind
        source: ./api.anveshak.in.crt
        target: /etc/nginx/conf.d/api.anveshak.in.crt
      - type: bind
        source: ./api.anveshak.in.pem
        target: /etc/nginx/conf.d/api.anveshak.in.pem
      - type: bind
        source: ./api_anveshak.conf
        target: /etc/nginx/conf.d/api_anveshak.conf
